# Generated by Django 4.1.4 on 2022-12-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='%Y-%m-%d')),
                ('trade_code', models.CharField(max_length=50)),
                ('high', models.CharField(max_length=50)),
                ('low', models.CharField(max_length=50)),
                ('openn', models.CharField(max_length=50)),
                ('close', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
            ],
        ),
    ]
